# on:
#   push:
#     branches:
#       - master

# name: Deploy website on push

# jobs:
#   web-deploy:
#     name: Deploy
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout latest code
#         uses: actions/checkout@v2.3.2

#       - name: Setup NodeJS
#         uses: actions/setup-node@v3
#         with:
#           node-version: latest

#       - name: Install build dependencies
#         run: npm install

#       - name: Build website
#         run: npm run build

#       - name: Copy .htaccess into dist
#         run: cp .htaccess dist/.htaccess

#       - name: Deploy to DreamHost via SFTP
#         uses: pressidium/sftp-deploy-action@v1.0.4
#         with:
#           server: "virginia.clubrunning.org"
#           username: "virginia_run"
#           password: ${{ secrets.FTP_PASSWORD }}
#           local_path: "./dist"
#           remote_path: "./virginia.clubrunning.org"
#           delete: false
name: Deploy via SFTP
on:
  push:
    branches:
      - master
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Deploy files via SFTP
        uses: pressidium/lftp-mirror-action@v1
        with:
          # SFTP credentials
          host: "virginia.clubrunning.org"
          port: 22
          user: "virginia_run"
          pass: ${{ secrets.FTP_PASSWORD }}
          # lftp settings
          onlyNewer: true
          settings: 'sftp:auto-confirm=yes'
          # Mirror command options
          localDir: './dist'
          remoteDir:  './virginia.clubrunning.org'
          reverse: true
          ignoreFile: '.lftp_ignore'
          options: '--verbose'